#!/bin/bash

script_path="$HOME/tmux_scripts"

tmux start-server

source ${script_path}/tmux_session_work
source ${script_path}/tmux_session_ttyt
#source ${script_path}/tmux_session_stuff

tmux attach-session -t ttyt
